name: read_cache_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  go_router: ^13.0.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6

flutter:

  uses-material-design: true
  # assets:
  #   - images/
